/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["api_schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Issue JWT tokens with an inspectable schema for drf-spectacular.
         *
         *     Emite tokens JWT con un esquema detectable por drf-spectacular.
         */
        post: operations["api_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Refresh JWT tokens with an inspectable schema for drf-spectacular.
         *
         *     Renueva tokens JWT con un esquema detectable por drf-spectacular.
         */
        post: operations["api_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/case-studies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for CaseStudy model. */
        get: operations["cms_case_studies_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/case-studies/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for CaseStudy model. */
        get: operations["cms_case_studies_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/faq-items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for FAQItem model. */
        get: operations["cms_faq_items_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/faq-items/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for FAQItem model. */
        get: operations["cms_faq_items_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/final-cta/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for FinalCTA model. */
        get: operations["cms_final_cta_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/final-cta/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for FinalCTA model. */
        get: operations["cms_final_cta_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/footer-link-groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for FooterLinkGroup model. */
        get: operations["cms_footer_link_groups_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/footer-link-groups/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for FooterLinkGroup model. */
        get: operations["cms_footer_link_groups_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/footer-links/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for FooterLink model. */
        get: operations["cms_footer_links_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/footer-links/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for FooterLink model. */
        get: operations["cms_footer_links_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/glimpse-images/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for GlimpseImage model. */
        get: operations["cms_glimpse_images_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/glimpse-images/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for GlimpseImage model. */
        get: operations["cms_glimpse_images_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/hero/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for the Hero section. */
        get: operations["cms_hero_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/hero/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for the Hero section. */
        get: operations["cms_hero_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/hero/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return the currently active Hero section. */
        get: operations["cms_hero_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/integrations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for Integration model. */
        get: operations["cms_integrations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/integrations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for Integration model. */
        get: operations["cms_integrations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/kpi-stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for KPIStat model. */
        get: operations["cms_kpi_stats_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/kpi-stats/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for KPIStat model. */
        get: operations["cms_kpi_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/navigation-menu/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only ViewSet for NavigationMenu with header/footer filtering. */
        get: operations["cms_navigation_menu_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/navigation-menu/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only ViewSet for NavigationMenu with header/footer filtering. */
        get: operations["cms_navigation_menu_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/navigation-menu/footer/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return footer navigation menu. */
        get: operations["cms_navigation_menu_footer_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/navigation-menu/header/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return header navigation menu. */
        get: operations["cms_navigation_menu_header_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/pricing-features/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for PricingFeature model. */
        get: operations["cms_pricing_features_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/pricing-features/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for PricingFeature model. */
        get: operations["cms_pricing_features_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/pricing-plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for PricingPlan model. */
        get: operations["cms_pricing_plans_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/pricing-plans/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for PricingPlan model. */
        get: operations["cms_pricing_plans_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/site-settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for SiteSettings (only one instance expected). */
        get: operations["cms_site_settings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/site-settings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for SiteSettings (only one instance expected). */
        get: operations["cms_site_settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/site-settings/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return the first (active) SiteSettings instance. */
        get: operations["cms_site_settings_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/solutions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for Solution model. */
        get: operations["cms_solutions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/solutions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for Solution model. */
        get: operations["cms_solutions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/testimonials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for Testimonial model. */
        get: operations["cms_testimonials_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/testimonials/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for Testimonial model. */
        get: operations["cms_testimonials_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/trust-logos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for TrustLogo model. */
        get: operations["cms_trust_logos_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/trust-logos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for TrustLogo model. */
        get: operations["cms_trust_logos_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/use-case-features/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for UseCaseFeature model. */
        get: operations["cms_use_case_features_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/use-case-features/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for UseCaseFeature model. */
        get: operations["cms_use_case_features_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/use-case-tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for UseCaseTag model. */
        get: operations["cms_use_case_tags_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/use-case-tags/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API for UseCaseTag model. */
        get: operations["cms_use_case_tags_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `pattern` - Subtle Pattern
         *     * `image` - Background Image
         *     * `solid` - Solid Color
         * @enum {string}
         */
        BgTypeEnum: "pattern" | "image" | "solid";
        /** @description Serializer for the CaseStudy model. */
        CaseStudy: {
            readonly id: number;
            readonly image_url: string;
            /** @description Category label (e.g., 'Traffic Flow', 'Public Safety'). */
            category: string;
            /** @description City or organization name (e.g., 'Metropolis'). */
            city: string;
            /** @description Title summarizing the key outcome (e.g., '20% Congestion Reduction'). */
            title: string;
            /** @description Short paragraph describing the results and how they were achieved. */
            summary: string;
            /**
             * Format: int64
             * @description Display order in the grid.
             */
            order?: number;
            /** @description Controls visibility on the landing page. */
            is_active?: boolean;
        };
        /** @description Serializer for the FAQItem model. */
        FAQItem: {
            readonly id: number;
            /** @description The FAQ question text. */
            question: string;
            /** @description The corresponding answer to the FAQ question. */
            answer: string;
            /**
             * Format: int64
             * @description Display order in the FAQ section.
             */
            order?: number;
            /** @description Controls visibility on the landing page. */
            is_active?: boolean;
        };
        /** @description Serializer for the FinalCTA model. */
        FinalCTA: {
            readonly id: number;
            /** @description Main headline for the final CTA (e.g., 'Ready to Build a Smarter Council?'). */
            heading: string;
            /** @description Supporting text that elaborates the CTA purpose. */
            subheading: string;
            /** @description Text for the main button. */
            primary_button_text?: string;
            /**
             * Format: uri
             * @description URL the primary button links to.
             */
            primary_button_url?: string;
            /** @description Optional text for a secondary button. */
            secondary_button_text?: string;
            /**
             * Format: uri
             * @description URL the secondary button links to.
             */
            secondary_button_url?: string;
            /**
             * Format: int64
             * @description Display order if multiple CTAs exist.
             */
            order?: number;
            /** @description Controls whether this CTA section is visible. */
            is_active?: boolean;
        };
        /** @description Serializer for the FooterLink model. */
        FooterLink: {
            readonly id: number;
            /** @description Parent link group (e.g., Product, Company, Legal). */
            group: number;
            /** @description Link label displayed in the footer (e.g., 'Privacy Policy'). */
            label: string;
            /**
             * Format: uri
             * @description URL the footer link points to.
             */
            url: string;
            /**
             * Format: int64
             * @description Order within the footer group.
             */
            order?: number;
            /** @description Controls visibility of this link. */
            is_active?: boolean;
        };
        /** @description Serializer for the FooterLinkGroup model. */
        FooterLinkGroup: {
            readonly id: number;
            /** @description Title of the footer link group (e.g., 'Product'). */
            title: string;
            /** @description List of link objects, each with 'label' and 'url'. */
            links?: unknown;
            /**
             * Format: int64
             * @description Display order for footer link groups.
             */
            order?: number;
            /** @description Controls visibility in the footer. */
            is_active?: boolean;
        };
        /** @description Serializer for the GlimpseImage model. */
        GlimpseImage: {
            readonly id: number;
            readonly image_url: string;
            /** @description Optional short title or label for the image. */
            title?: string;
            /** @description Optional short caption describing the image. */
            caption?: string;
            /**
             * Format: int64
             * @description Display order in the frontend grid.
             */
            order?: number;
            /** @description Controls visibility on the landing page. */
            is_active?: boolean;
        };
        /** @description Serializer for the Hero model. */
        Hero: {
            readonly id: number;
            title?: string;
            /** @description Optional supporting text below the title. */
            subtitle?: string;
            cta_primary_label?: string;
            cta_primary_href?: string;
            cta_secondary_label?: string;
            cta_secondary_href?: string;
            bg_type?: components["schemas"]["BgTypeEnum"];
            readonly bg_media_url: string;
            /** @description Only one hero should be active at a time. */
            is_active?: boolean;
        };
        /** @description Serializer for the Integration model. */
        Integration: {
            readonly id: number;
            /** @description Integration name (e.g., 'Esri', 'Salesforce'). */
            name: string;
            readonly logo_url: string;
            /**
             * Format: uri
             * @description Optional URL to the partner or product page.
             */
            website_url?: string;
            /**
             * Format: int64
             * @description Display order in the integrations grid.
             */
            order?: number;
            /** @description Controls whether this integration is visible. */
            is_active?: boolean;
        };
        /** @description Serializer for the KPIStat model. */
        KPIStat: {
            readonly id: number;
            /** @description Short description of the KPI (e.g. 'Faster Permit Approvals'). */
            label: string;
            /** @description Numeric or symbolic KPI value (e.g. '30%', '15M+', '4.9/5'). */
            value: string;
            /**
             * Format: int64
             * @description Display order in the KPI grid.
             */
            order?: number;
            /** @description Controls whether this KPI is visible. */
            is_active?: boolean;
        };
        /**
         * @description * `essentials` - Essentials
         *     * `professional` - Professional
         *     * `enterprise` - Enterprise
         * @enum {string}
         */
        NameEnum: "essentials" | "professional" | "enterprise";
        /** @description Serializer for individual navigation items. */
        NavItem: {
            readonly id: number;
            label: string;
            /** @description URL or hash link (e.g. #solutions) */
            href: string;
            /** Format: int64 */
            order?: number;
        };
        /** @description Serializer for NavigationMenu including its related items. */
        NavigationMenu: {
            readonly id: number;
            name: string;
            placement?: components["schemas"]["PlacementEnum"];
            readonly items: components["schemas"]["NavItem"][];
        };
        /**
         * @description * `header` - Header
         *     * `footer` - Footer
         * @enum {string}
         */
        PlacementEnum: "header" | "footer";
        /** @description Serializer for the PricingFeature model. */
        PricingFeature: {
            readonly id: number;
            /** @description The pricing plan this feature belongs to. */
            plan: number;
            /** @description Short description of the feature. */
            description: string;
            /**
             * Format: int64
             * @description Display order within the plan.
             */
            order?: number;
            /** @description Indicates if the feature is included or optional. */
            included?: boolean;
        };
        /** @description Serializer for the PricingPlan model. */
        PricingPlan: {
            readonly id: number;
            /**
             * @description Plan name or tier (e.g., Essentials, Professional, Enterprise).
             *
             *     * `essentials` - Essentials
             *     * `professional` - Professional
             *     * `enterprise` - Enterprise
             */
            name: components["schemas"]["NameEnum"];
            /** @description Short description of the plan’s target audience. */
            description: string;
            /** @description Displayed price (e.g., '$499/mo' or 'Contact Us'). */
            price: string;
            /** @description Marks this plan as 'Most Popular'. */
            highlight?: boolean;
            /**
             * Format: int64
             * @description Display order for frontend rendering.
             */
            order?: number;
            /** @description List of included features. */
            features?: unknown;
            /** @description Controls whether the plan is visible on the pricing section. */
            is_active?: boolean;
        };
        /** @description Serializer for the SiteSettings model. */
        SiteSettings: {
            readonly id: number;
            site_name?: string;
            theme_primary?: string;
            theme_bg_light?: string;
            theme_bg_dark?: string;
            /** Format: uri */
            twitter_url?: string;
            /** Format: uri */
            linkedin_url?: string;
            /** Format: uri */
            youtube_url?: string;
            meta_title?: string;
            meta_description?: string;
            readonly logo_url: string;
            readonly og_image_url: string;
        };
        /** @description Serializer for the Solution model. */
        Solution: {
            readonly id: number;
            /** @description Material icon name (e.g., 'map', 'engineering', 'emergency_home'). */
            icon: string;
            /** @description Solution title. */
            title: string;
            /** @description Short description of what this solution offers. */
            description: string;
            /**
             * Format: int64
             * @description Display order on the frontend.
             */
            order?: number;
            /** @description Controls visibility on the site. */
            is_active?: boolean;
        };
        /** @description Serializer for the Testimonial model. */
        Testimonial: {
            readonly id: number;
            /** @description Quoted testimonial text. */
            quote: string;
            /** @description Full name of the testimonial author. */
            author_name: string;
            /** @description Author’s title or role (e.g., 'City Planner'). */
            author_title: string;
            /** @description Name of the organization or department. */
            organization: string;
            readonly author_photo_url: string;
            /** @description Mark if testimonial is verified. */
            verified?: boolean;
            /** @description Optional label for the first impact metric (e.g., 'Faster Reviews'). */
            stat_1_label?: string;
            /** @description Numeric/statistical value for the first metric (e.g., '50%'). */
            stat_1_value?: string;
            /** @description Optional label for the second impact metric (e.g., 'Productivity Boost'). */
            stat_2_label?: string;
            /** @description Numeric/statistical value for the second metric (e.g., '20%'). */
            stat_2_value?: string;
            /**
             * Format: int64
             * @description Display order in the frontend.
             */
            order?: number;
            /** @description Controls visibility on the landing page. */
            is_active?: boolean;
        };
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /** @description Serializer for the TrustLogo model. */
        TrustLogo: {
            readonly id: number;
            /** @description Partner or organization name. */
            name: string;
            readonly image_url: string;
            /**
             * Format: uri
             * @description Optional link to the partner’s website.
             */
            link?: string | null;
            /**
             * Format: int64
             * @description Display order on the page.
             */
            order?: number;
            /** @description Controls whether the logo appears on the site. */
            is_active?: boolean;
        };
        /** @description Serializer for the UseCaseFeature model. */
        UseCaseFeature: {
            readonly id: number;
            /** @description Feature title (e.g., 'Streamline Permit Approvals'). */
            title: string;
            /** @description Detailed explanation of how this feature solves a real-world challenge. */
            description: string;
            readonly image_url: string;
            readonly tags: components["schemas"]["UseCaseTag"][];
            /**
             * Format: int64
             * @description Display order on the frontend.
             */
            order?: number;
            /** @description Controls visibility on the landing page. */
            is_active?: boolean;
        };
        /** @description Serializer for the UseCaseTag model. */
        UseCaseTag: {
            readonly id: number;
            /** @description Tag name (e.g., 'Permit Management', 'Code Enforcement'). */
            name: string;
            /** @description URL-friendly version of the tag name. */
            slug: string;
            /** @description Optional short description for this tag. */
            description?: string;
            /**
             * Format: int64
             * @description Display order for the frontend.
             */
            order?: number;
            /** @description Controls whether the tag is visible or selectable. */
            is_active?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    api_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    cms_case_studies_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseStudy"][];
                };
            };
        };
    };
    cms_case_studies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Case Study. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseStudy"];
                };
            };
        };
    };
    cms_faq_items_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FAQItem"][];
                };
            };
        };
    };
    cms_faq_items_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this FAQ Item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FAQItem"];
                };
            };
        };
    };
    cms_final_cta_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalCTA"][];
                };
            };
        };
    };
    cms_final_cta_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Final CTA. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalCTA"];
                };
            };
        };
    };
    cms_footer_link_groups_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FooterLinkGroup"][];
                };
            };
        };
    };
    cms_footer_link_groups_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Footer Link Group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FooterLinkGroup"];
                };
            };
        };
    };
    cms_footer_links_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FooterLink"][];
                };
            };
        };
    };
    cms_footer_links_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Footer Link. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FooterLink"];
                };
            };
        };
    };
    cms_glimpse_images_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlimpseImage"][];
                };
            };
        };
    };
    cms_glimpse_images_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Glimpse Image. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlimpseImage"];
                };
            };
        };
    };
    cms_hero_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hero"][];
                };
            };
        };
    };
    cms_hero_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Hero Section. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hero"];
                };
            };
        };
    };
    cms_hero_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hero"];
                };
            };
        };
    };
    cms_integrations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Integration"][];
                };
            };
        };
    };
    cms_integrations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Integration. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Integration"];
                };
            };
        };
    };
    cms_kpi_stats_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPIStat"][];
                };
            };
        };
    };
    cms_kpi_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this KPI Statistic. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPIStat"];
                };
            };
        };
    };
    cms_navigation_menu_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationMenu"][];
                };
            };
        };
    };
    cms_navigation_menu_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this navigation menu. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationMenu"];
                };
            };
        };
    };
    cms_navigation_menu_footer_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationMenu"];
                };
            };
        };
    };
    cms_navigation_menu_header_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationMenu"];
                };
            };
        };
    };
    cms_pricing_features_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingFeature"][];
                };
            };
        };
    };
    cms_pricing_features_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Pricing Feature. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingFeature"];
                };
            };
        };
    };
    cms_pricing_plans_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingPlan"][];
                };
            };
        };
    };
    cms_pricing_plans_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Pricing Plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingPlan"];
                };
            };
        };
    };
    cms_site_settings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettings"][];
                };
            };
        };
    };
    cms_site_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Site Settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettings"];
                };
            };
        };
    };
    cms_site_settings_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettings"];
                };
            };
        };
    };
    cms_solutions_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Solution"][];
                };
            };
        };
    };
    cms_solutions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Solution. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Solution"];
                };
            };
        };
    };
    cms_testimonials_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Testimonial"][];
                };
            };
        };
    };
    cms_testimonials_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Testimonial. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Testimonial"];
                };
            };
        };
    };
    cms_trust_logos_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustLogo"][];
                };
            };
        };
    };
    cms_trust_logos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Trust Logo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustLogo"];
                };
            };
        };
    };
    cms_use_case_features_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UseCaseFeature"][];
                };
            };
        };
    };
    cms_use_case_features_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Use Case Feature. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UseCaseFeature"];
                };
            };
        };
    };
    cms_use_case_tags_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UseCaseTag"][];
                };
            };
        };
    };
    cms_use_case_tags_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Use Case Tag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UseCaseTag"];
                };
            };
        };
    };
}
